development:
  adapter: postgresql
  encoding: utf8
  database: playme_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: playme_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: playme_production
  pool: 5
  username: 
  password: